# Generated by Django 5.1 on 2024-08-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_category_model', '0002_remove_taskcategorymodel_task_model'),
        ('task_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task_category_model',
            field=models.ManyToManyField(to='task_category_model.taskcategorymodel'),
        ),
    ]
