# Generated by Django 5.1 on 2024-08-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicin',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
