# Generated by Django 5.1 on 2024-08-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_category_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategorymodel',
            name='task_model',
        ),
    ]
