# Generated by Django 5.1 on 2024-08-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentRegistration',
            new_name='StudentRegistrationModel',
        ),
    ]
